PROMPT Скрипт создания пользователя test
CREATE USER "test"
    PROFILE "DEFAULT"
IDENTIFIED BY "123456"
    DEFAULT TABLESPACE "USERS"
    QUOTA UNLIMITED ON cwmlite
    QUOTA UNLIMITED ON drsys
    QUOTA UNLIMITED ON example
    QUOTA UNLIMITED ON indx
    QUOTA UNLIMITED ON system
    QUOTA UNLIMITED ON temp
    QUOTA UNLIMITED ON tools
    QUOTA UNLIMITED ON users
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "test";
GRANT "DBA" TO "test";