PROMPT Скрипт создания пользователя kruglovvs
CREATE USER "KRUGLOVVS"
    PROFILE "DEFAULT"
IDENTIFIED BY "123456"
    DEFAULT TABLESPACE "USERS"
    QUOTA UNLIMITED ON sysaux
    QUOTA UNLIMITED ON system
    QUOTA UNLIMITED ON users
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "KRUGLOVVS";
GRANT "DBA" TO "KRUGLOVVS";